name: Release

on:
  push:
    branches: [ master, beta, integrated, beta-integrated ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@master
        with:
          dotnet-version: 3.1.x
        env:
          DOTNET_NOLOGO: 1
          DOTNET_CLI_TELEMETRY_OPTOUT: 1

      - name: Setup BUTR GPR
        uses: actions/setup-dotnet@master
        with:
          source-url: https://nuget.pkg.github.com/BUTR/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
          DOTNET_NOLOGO: 1
          DOTNET_CLI_TELEMETRY_OPTOUT: 1
          
#     - name: Set build version
#       run: ((Get-Content .\Directory.Build.props -Raw) -replace "<Version>(\d+)\.(\d+)\.(\d+)\.0<\/Version>", "<Version>`$1.`$2.`$3.${{github.run_number}}</Version>") | Set-Content .\Directory.Build.props

      - name: Build BannerlordCheats
        run: dotnet build BannerlordCheats.csproj  --configuration Release -p:GameFolder="$PWD\game"
        env:
          DOTNET_NOLOGO: 1
          DOTNET_CLI_TELEMETRY_OPTOUT: 1
          
      - name: Get Versions
        id: versions
        run: |
          $ModVersion = Get-Content .\Directory.Build.props | Select-String -Pattern "<Version>([\d.]+)<\/Version>" | % { $($_.Matches.Groups[1]).Value }
          $ModVersion = $ModVersion.TrimEnd(".0")	
          If ($ModVersion -notmatch "\.") { $ModVersion = "$ModVersion.0" }
          echo "::set-output name=mod_version::$ModVersion"
          $GameVersion = Get-Content .\Directory.Build.props | Select-String -Pattern "<GameVersion>([\d.]+)<\/GameVersion>" | % { $($_.Matches.Groups[1]).Value }
          echo "::set-output name=game_version::$GameVersion"
          $GameBranch = Get-Content .\Directory.Build.props | Select-String -Pattern "<GameBranch>(.+)<\/GameBranch>" | % { $($_.Matches.Groups[1]).Value }
          echo "::set-output name=game_branch::$GameBranch"
          $AdditionalInfo = Get-Content .\Directory.Build.props | Select-String -Pattern "<AdditionalInfo>(.*)<\/AdditionalInfo>" | % { $($_.Matches.Groups[1]).Value }
          $AdditionalInfoEscaped = $AdditionalInfo -replace " ", "."
          If ($AdditionalInfoEscaped) { $AdditionalInfoEscaped = "$AdditionalInfoEscaped." }
          echo "::set-output name=additional_info_escaped::$AdditionalInfoEscaped"
          If ($AdditionalInfo) { $AdditionalInfo = " $AdditionalInfo" }
          echo "::set-output name=additional_info::$AdditionalInfo"
          $RepoBranch = "${{github.ref}}"
          $RepoBranch = $RepoBranch.Split("/")[-1]
          If ($RepoBranch -eq "master") { $RepoBranch = "" }
          If ($RepoBranch) { $RepoBranch = "-$RepoBranch" }
          echo "::set-output name=repo_branch::$RepoBranch"

      - name: Package Mod Files
        run: 7z a -tzip BannerlordCheats.v${{steps.versions.outputs.mod_version}}.${{steps.versions.outputs.additional_info_escaped}}${{steps.versions.outputs.game_branch}}.e${{steps.versions.outputs.game_version}}.zip ./game/Modules/*

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: BannerlordCheats.v${{steps.versions.outputs.mod_version}}.${{steps.versions.outputs.additional_info_escaped}}${{steps.versions.outputs.game_branch}}.e${{steps.versions.outputs.game_version}}
          path: ./game/Modules/*

      - name: Create Release
        uses: actions/create-release@v1
        id: create_release
        with:
          tag_name: v${{steps.versions.outputs.mod_version}}${{steps.versions.outputs.repo_branch}}
          release_name: Release v${{steps.versions.outputs.mod_version}}${{steps.versions.outputs.additional_info}} for ${{steps.versions.outputs.game_branch}} e${{steps.versions.outputs.game_version}}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Upload Release Asset
        id: upload_release_asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{steps.create_release.outputs.upload_url}}
          asset_path: ./BannerlordCheats.v${{steps.versions.outputs.mod_version}}.${{steps.versions.outputs.additional_info_escaped}}${{steps.versions.outputs.game_branch}}.e${{steps.versions.outputs.game_version}}.zip
          asset_name: BannerlordCheats.v${{steps.versions.outputs.mod_version}}.${{steps.versions.outputs.additional_info_escaped}}${{steps.versions.outputs.game_branch}}.e${{steps.versions.outputs.game_version}}.zip
          asset_content_type: application/zip
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
